version: '3'

services:
  # api
  local:
    build: .
    working_dir: /usr/src/app/
    volumes:
      - ./:/usr/src/app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn dev'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/status']
      interval: 600s
      timeout: 10s
      retries: 5
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3000:3000
    depends_on:
      - db

  # database
  db:
    image: postgres:15
    expose:
      - 5432
    ports:
      - 5432:5432
    command: postgres -D /run/pgsql-15-data -F -c logging_collector=on
    volumes:
      - ./data/dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
      - LOGGING_COLLECTOR='on'
